PDA-42 process definition list endpoint
entando/entando-process-driven-plugin pull request #12
Opened 2019-11-27 14:31 UTC by ffleandro

2019-11-27 14:32 UTC, entando-service commented
Something went wrong. Investigate!

2019-11-27 14:37 UTC, entando-service commented
Something went wrong. Investigate!

2019-11-28 13:59 UTC, werbth requested changes

2019-11-28 13:59 UTC, werbth commented on src/main/java/org/entando/plugins/pda/controller/AuthPermissions.java
> +    public static final String PROCESS_GET = "process-get";
This constant is not being used.

2019-11-29 13:10 UTC, entando-service commented
Something went wrong. Investigate!

2019-11-29 14:05 UTC, werbth commented
retest this please

2019-11-29 14:05 UTC, entando-service commented
Something went wrong. Investigate!

2019-11-29 14:11 UTC, ffleandro commented
Retest this please

2019-11-29 14:12 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-02 11:54 UTC, ffleandro commented
Retest this please

2019-12-02 11:55 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-02 17:27 UTC, werbth commented
retest this please

2019-12-02 17:28 UTC, entando-service commented
All is well

2019-12-02 17:31 UTC, werbth approved these changes

2019-12-02 17:37 UTC, werbth commented
retest this please

2019-12-02 17:38 UTC, entando-service commented
All is well

2019-12-02 17:45 UTC, merged