PDA-54 Adding task form controller
entando/entando-process-driven-plugin pull request #21
Opened 2019-12-19 18:30 UTC by BrenoQVDS

2019-12-19 18:30 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-20 12:15 UTC, ffleandro requested changes

2019-12-20 12:15 UTC, ffleandro commented on src/main/java/org/entando/plugins/pda/controller/AuthPermissions.java
> +    public static final String TASK_DEFINITION_FORM = "task-definition-form";
Should only be `TASK_FORM` because it corresponds to a task instance

2019-12-20 12:15 UTC, ffleandro commented on src/main/java/org/entando/plugins/pda/controller/task/TaskFormController.java
> +    @GetMapping(path = "/definitions/{taskId}/form", produces = {APPLICATION_JSON_VALUE})
Should not have a mapping path

2019-12-20 12:15 UTC, ffleandro commented on src/main/java/org/entando/plugins/pda/controller/task/TaskFormController.java
> +@RequestMapping(path = "/connections/{connId}/tasks")
Path should be `/connections/{connId}/tasks/{taskId}/form`

2019-12-20 12:15 UTC, ffleandro commented on src/test/java/org/entando/plugins/pda/controller/task/TaskFormControllerIntegrationTest.java
> +        MvcResult result = mockMvc.perform(get("/connections/fakeProduction/tasks/definitions/{id}/form"
Fix path according to previous comment

2019-12-20 12:15 UTC, ffleandro commented on src/test/java/org/entando/plugins/pda/controller/task/TaskFormControllerIntegrationTest.java
> +        mockMvc.perform(get("/connections/fakeProduction/tasks/definitions/{id}/form"
Fix path according to previous comment

2019-12-20 18:29 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-20 18:33 UTC, entando-service commented
Something went wrong. Investigate!

2019-12-26 19:57 UTC, ffleandro approved these changes

2019-12-26 20:07 UTC, entando-service commented
All is well

2019-12-26 20:07 UTC, merged