PDA-82 Form Widgets
entando/entando-process-driven-plugin pull request #47
Opened 2020-02-13 22:43 UTC by ffleandro

Added Support for the following form widgets:
    Combo, Slider, TextArea, Radio, Double, Date, MultipleSelector and InputList;

2020-02-13 22:44 UTC, entando-service commented
Something went wrong. Investigate!

2020-02-17 10:28 UTC, werbth requested changes
@ffleandro Please, resolve only the duplication for now. The other comments we are going to solve later.

2020-02-17 10:28 UTC, werbth commented on src/main/java/org/entando/plugins/pda/serializer/JsonSchemaFormSerializer.java
> +@SuppressWarnings({"PMD.TooManyMethods", "PMD.GodClass"})
We should solve GodClass (later)

2020-02-17 10:28 UTC, werbth commented on src/main/java/org/entando/plugins/pda/serializer/JsonSchemaFormSerializer.java
> +    @SuppressWarnings("PMD.CyclomaticComplexity")
We should solve CyclomaticComplexity (later)

2020-02-17 10:28 UTC, werbth commented on src/main/java/org/entando/plugins/pda/serializer/JsonSchemaFormSerializer.java
> +        for (FormFieldSelector.Option option : field.getOptions()) {
This for loop is a duplication for the one in the method below, please resolve the duplication.

2020-02-17 12:46 UTC, entando-service commented
Something went wrong. Investigate!

2020-02-17 13:29 UTC, werbth commented
Retest this please

2020-02-17 13:30 UTC, entando-service commented
Something went wrong. Investigate!

2020-02-17 13:53 UTC, entando-service commented
Something went wrong. Investigate!

2020-02-17 14:11 UTC, entando-service commented
All is well

2020-02-17 14:14 UTC, werbth approved these changes

2020-02-17 14:14 UTC, merged